package com.javacourse.classes;

public class Browser {

    public void navigate(String address) {

        //when the cache argument was added to this method
        //we needed to modify the method call here
        //but ONLY here! not in our main method or anywhere else!

        String ip   = findIpAddress(address, true);
        String html = sendHttpRequest(ip);

        System.out.println(html);
    }
    //navigate

    //these methods were made private
    //because the user of this class only cares about the navigate method
    //they are even autogenerated as private by default by intellij!

    private String findIpAddress(String address, boolean cache) {
        return "127.0.0.1";
    }
    //findIpAddress

    private String sendHttpRequest(String ip) {
        return "<html></html>";
    }
    //sendHttpRequest
}
//Browser

//eof
